### PR TITLE
examples/raylib: fix build in Ubuntu Linux 24 (GCC 13.3.0)

### PR DESCRIPTION
**Pull request by gabrielssanches**
gcc 13.3.0 spits out errors regaring timespec:

```
nbnet/examples/raylib/server.c:404:16: error: variable ‘t’ has initializer but incomplete type
  404 |         struct timespec t = {.tv_sec = nanos / 999999999, .tv_nsec = nanos % 999999999};
      |                ^~~~~~~~
```

c99 includes time.h but timespec is not added automatically

changing the C standar from c99 to gnu99 fix this issue

### CODE REVIEW

**Comment by gabrielssanches** [comment]
or add -DCMAKE_C_FLAGS="-D_GNU_SOURCE" to cmake (then patch the readme file instead), you decide

**Comment by nathhB** [comment]
@gabrielssanches thank you. I don't think we should change the C standard as nbnet is intended to be a C99 library.

**Comment by gabrielssanches** [comment]
changes made

**Comment by nathhB** [comment]
@gabrielssanches thank you. Looks like some pipeline jobs are failing, but it seems to be due to CMake and Python deprecation. I'll fix those in master and rerun the pipeline in this MR and merge whell they all pass.

**Review by nathhB — APPROVED** [review]
